name: ellena
description: "AI-powered product manager that automates task management"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^8.0.3
  
  # Local storage
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_markdown: ^0.7.7
  # UI components
  flutter_chat_ui: ^1.6.10
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.9
  
  # AI and utilities
  http: ^1.1.0
  intl: ^0.18.1
  uuid: ^4.5.1
  logger: ^1.1.0
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.10
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
